# Generated by Django 4.1.3 on 2024-06-26 08:50

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_duration_options_alter_contract_created_at_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='duration',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='duration',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='duration',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is recurring'),
        ),
        migrations.AddField(
            model_name='duration',
            name='reminder_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Reminder days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='durationevent',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is recurring'),
        ),
        migrations.AddField(
            model_name='durationevent',
            name='reminder_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Reminder days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duration',
            name='no_of_days',
            field=models.PositiveIntegerField(verbose_name='No of days'),
        ),
        migrations.AlterField(
            model_name='durationevent',
            name='no_of_days',
            field=models.PositiveIntegerField(verbose_name='No of days'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='duration',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "contract_durationevent" ("created_at", "created_by_id", "id", "is_deleted", "is_recurring", "modified_at", "modified_by_id", "no_of_days", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reminder_days", "type") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_recurring", NEW."modified_at", NEW."modified_by_id", NEW."no_of_days", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."reminder_days", NEW."type"); RETURN NULL;', hash='8f8f60f530c8d00a0e2b0d4b325f652915ae70fb', operation='INSERT', pgid='pgtrigger_snapshot_insert_599b2', table='contract_duration', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='duration',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "contract_durationevent" ("created_at", "created_by_id", "id", "is_deleted", "is_recurring", "modified_at", "modified_by_id", "no_of_days", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reminder_days", "type") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_recurring", NEW."modified_at", NEW."modified_by_id", NEW."no_of_days", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."reminder_days", NEW."type"); RETURN NULL;', hash='d2bcea69b6763b67f3cb3e6cdddae5f01aad6f0f', operation='UPDATE', pgid='pgtrigger_snapshot_update_daf19', table='contract_duration', when='AFTER')),
        ),
    ]
