# Generated by Django 4.1.3 on 2024-07-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_payment_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='contract.payment'),
        ),
    ]
