# Generated by Django 4.1.3 on 2024-07-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_reminder_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contract.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='contract',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contract.contract', verbose_name='Contract'),
        ),
    ]
