# Generated by Django 4.2.20 on 2025-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_contracts_created_by"),
        ("contract", "0010_alter_contract_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="paths",
            field=models.ManyToManyField(
                blank=True,
                related_name="contracts",
                to="core.path",
                verbose_name="Paths",
            ),
        ),
    ]
