version: "3.9"
   
services:
  backend:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             DJANGO_SUPERUSER_PASSWORD=psw \
             python manage.py createsuperuser --username=admin --email=admin@admin.com --noinput
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/isc_mysql/data
    env_file: .env
    ports:
      - "3306:3306"
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/redis