# Generated by Django 4.1.2 on 2022-10-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priorities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
