# Generated by Django 4.1.3 on 2023-04-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='notification',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='notification',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notification',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_notificationevent" ("action", "action_at", "action_by_id", "created_by_id", "id", "is_deleted", "is_read", "model", "obj", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."action", NEW."action_at", NEW."action_by_id", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_read", NEW."model", NEW."obj", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='69c67c72dab437d51746c41368bce5d574ed44cb', operation='INSERT', pgid='pgtrigger_snapshot_insert_c38ef', table='core_notification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notification',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_notificationevent" ("action", "action_at", "action_by_id", "created_by_id", "id", "is_deleted", "is_read", "model", "obj", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."action", NEW."action_at", NEW."action_by_id", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_read", NEW."model", NEW."obj", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='39d0b746985fcad27615becc612aae1da60152ae', operation='UPDATE', pgid='pgtrigger_snapshot_update_be18e', table='core_notification', when='AFTER')),
        ),
    ]
