# Generated by Django 4.1.3 on 2023-05-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_path_snapshot_insert_and_more'),]
