# Generated by Django 4.1.2 on 2022-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='attachment',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Attachment'),
        ),
    ]
