# Generated by Django 4.1.2 on 2022-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments_created_at_comments_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='case',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
