# Generated by Django 4.1.2 on 2022-10-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='case',
            new_name='case_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='hearing_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='task_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
