# Generated by Django 4.1.3 on 2023-05-06 06:18

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_rename_mptt_level_path_level_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='notification',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='notification',
            name='snapshot_update',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='model',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='model',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='obj',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='object_id',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notification',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_notificationevent" ("action", "action_at", "action_by_id", "content_type_id", "created_by_id", "id", "is_deleted", "is_read", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."action", NEW."action_at", NEW."action_by_id", NEW."content_type_id", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_read", NEW."object_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='7fd5d116b4ef4dcef12d63d6a6a937b7c459da52', operation='INSERT', pgid='pgtrigger_snapshot_insert_c38ef', table='core_notification', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notification',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_notificationevent" ("action", "action_at", "action_by_id", "content_type_id", "created_by_id", "id", "is_deleted", "is_read", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "user_id") VALUES (NEW."action", NEW."action_at", NEW."action_by_id", NEW."content_type_id", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."is_read", NEW."object_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."role", NEW."user_id"); RETURN NULL;', hash='9c6f6d4f91cdd8eb213044355fcb6a4a04604e75', operation='UPDATE', pgid='pgtrigger_snapshot_update_be18e', table='core_notification', when='AFTER')),
        ),
    ]
