# Generated by Django 4.1.3 on 2023-05-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_notification_snapshot_insert_and_more'),
    ]

    operations = [

    ]
