# Generated by Django 4.1.2 on 2022-11-03 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documents_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='attachment',
            field=models.FileField(upload_to='contracts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'git'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='attachment',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'git'])], verbose_name='Attachment'),
        ),
    ]
