# Generated by Django 4.1.2 on 2022-10-13 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_rename_case_comments_case_id_comments_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=250, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_replies', to='core.replies', verbose_name='Reply'),
        ),
    ]
