# Generated by Django 4.1.3 on 2022-11-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contracts_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
