# Generated by Django 4.1.2 on 2022-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_replies_comments_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='comment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
