# Generated by Django 4.1.3 on 2023-08-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pathevent_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
