# Generated by Django 4.1.2 on 2022-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_replies_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='reply',
            field=models.CharField(max_length=250, verbose_name='Reply'),
        ),
    ]
