# Generated by Django 4.1.3 on 2022-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comments_created_at_alter_comments_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
    ]
