# Generated by Django 4.1.3 on 2023-01-24 08:48

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_documents_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='documents',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='documents',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='documents',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='documentsevent',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folder'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='documents',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_documentsevent" ("attachment", "case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "name", "path_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."attachment", NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."path_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='1df997c63449ffe68474f546ca9214ab0eb12a24', operation='INSERT', pgid='pgtrigger_snapshot_insert_49b87', table='core_documents', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='documents',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_documentsevent" ("attachment", "case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "name", "path_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."attachment", NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."path_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='ce71217e4c699f4174d9617dc328e27758d1b79e', operation='UPDATE', pgid='pgtrigger_snapshot_update_c495f', table='core_documents', when='AFTER')),
        ),
    ]
