# Generated by Django 4.1.3 on 2023-08-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_mptt_level_path_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
