# Generated by Django 4.1.3 on 2022-11-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comments_is_deleted_contracts_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Comment'),
        ),
    ]
