# Generated by Django 4.1.3 on 2024-04-02 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_path_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['name'], 'verbose_name': 'Court', 'verbose_name_plural': 'Courts'},
        ),
        migrations.AlterField(
            model_name='path',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
