# Generated by Django 4.1.3 on 2023-01-30 10:30

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_path_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='path',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Litigation Case'),
        ),
        migrations.AddField(
            model_name='pathevent',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Litigation Case'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "id", "is_deleted", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='58436977ffb8c214b34c8aa1d243bb96578a84cf', operation='INSERT', pgid='pgtrigger_snapshot_insert_5eab7', table='core_path', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "id", "is_deleted", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='5ddffd839e19d5006b5059fe554ef38c13439895', operation='UPDATE', pgid='pgtrigger_snapshot_update_56fb9', table='core_path', when='AFTER')),
        ),
    ]
