# Generated by Django 4.1.3 on 2024-06-14 12:17

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_court_options_alter_path_created_by'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='comments',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='comments',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='comments',
            name='contract_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentsevent',
            name='contract_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comments',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_commentsevent" ("case_id", "comment", "contract_id", "created_at", "created_by_id", "event_id", "folder_id", "hearing_id", "id", "is_deleted", "modified_at", "modified_by_id", "notation_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id") VALUES (NEW."case_id", NEW."comment", NEW."contract_id", NEW."created_at", NEW."created_by_id", NEW."event_id", NEW."folder_id", NEW."hearing_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."notation_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."task_id"); RETURN NULL;', hash='7dce0250a336f3481308ab30ebaa2752e000a737', operation='INSERT', pgid='pgtrigger_snapshot_insert_cf925', table='core_comments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comments',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_commentsevent" ("case_id", "comment", "contract_id", "created_at", "created_by_id", "event_id", "folder_id", "hearing_id", "id", "is_deleted", "modified_at", "modified_by_id", "notation_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id") VALUES (NEW."case_id", NEW."comment", NEW."contract_id", NEW."created_at", NEW."created_by_id", NEW."event_id", NEW."folder_id", NEW."hearing_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."notation_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."task_id"); RETURN NULL;', hash='5a0029a0268cd9637632dc20bce590afd98b482c', operation='UPDATE', pgid='pgtrigger_snapshot_update_eb534', table='core_comments', when='AFTER')),
        ),
    ]
