# Generated by Django 4.1.3 on 2023-02-02 06:53

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_path_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='path',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='pathevent',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folder'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='398e501522a5c5bd8ce6ed3492443d55d52f0cdb', operation='INSERT', pgid='pgtrigger_snapshot_insert_5eab7', table='core_path', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='1ec17e859cef3a50769967cf89ff7733233d02c5', operation='UPDATE', pgid='pgtrigger_snapshot_update_56fb9', table='core_path', when='AFTER')),
        ),
    ]
