# Generated by Django 4.1.3 on 2024-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_comments_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='contract_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contract'),
        ),
    ]
