# Generated by Django 4.1.3 on 2023-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_path_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pathevent',
            name='name',
            field=models.CharField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=50),
        ),
    ]
