# Generated by Django 4.1.3 on 2024-07-13 06:28

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_path_contract_id'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='status',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='status',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='status',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_statusevent" ("id", "is_completed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", NEW."is_completed", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;', hash='f71ac1e0b0b967c6d79763be3c15262010ccd0d5', operation='INSERT', pgid='pgtrigger_snapshot_insert_0f7bb', table='core_status', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_statusevent" ("id", "is_completed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", NEW."is_completed", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;', hash='739cd3d7235f5f66cb7e5770f7b2e47f65c6062d', operation='UPDATE', pgid='pgtrigger_snapshot_update_eb6d5', table='core_status', when='AFTER')),
        ),
    ]
