# Generated by Django 4.1.3 on 2023-01-14 18:18

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_statusevent_status_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="status",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="status",
            name="snapshot_update",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="status",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_statusevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="cb8f4753b6405749f4124f1d18c1f1290856949a",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_0f7bb",
                    table="core_status",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="status",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_statusevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="2694667a700e74f109c508272de3326821aa1b28",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_eb6d5",
                    table="core_status",
                    when="AFTER",
                ),
            ),
        ),
    ]
