# Generated by Django 4.1.3 on 2024-07-30 08:52

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_status_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='status',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='status',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='status',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is Done'),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is Done'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_statusevent" ("id", "is_completed", "is_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", NEW."is_completed", NEW."is_done", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;', hash='87c6fe9a2f609954d95736505b7221da7297fa0f', operation='INSERT', pgid='pgtrigger_snapshot_insert_0f7bb', table='core_status', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_statusevent" ("id", "is_completed", "is_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."id", NEW."is_completed", NEW."is_done", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."status"); RETURN NULL;', hash='1756ef9286041a83d5cec369b61466a218ca584e', operation='UPDATE', pgid='pgtrigger_snapshot_update_eb6d5', table='core_status', when='AFTER')),
        ),
    ]
