# Generated by Django 4.1.3 on 2023-02-13 06:12

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_path_name_alter_pathevent_name'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='path',
            name='snapshot_update',
        ),
        migrations.RemoveField(
            model_name='path',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pathevent',
            name='is_deleted',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='c073e5d6de8cb65dc5a32398dfe38846d4b0ff66', operation='INSERT', pgid='pgtrigger_snapshot_insert_5eab7', table='core_path', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='path',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_pathevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "level", "lft", "modified_at", "modified_by_id", "name", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rght", "tree_id") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."level", NEW."lft", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."rght", NEW."tree_id"); RETURN NULL;', hash='73540291db6885bf6806f3abb0c0de28b512ff4c', operation='UPDATE', pgid='pgtrigger_snapshot_update_56fb9', table='core_path', when='AFTER')),
        ),
    ]
