# Generated by Django 4.1.3 on 2023-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_directory_directoryevent_directory_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="sub_directory",
            field=models.ManyToManyField(
                blank=True, to="core.directory", verbose_name="Sub directory"
            ),
        ),
    ]
