# Generated by Django 4.2.20 on 2025-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_commentsevent_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-action_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[(0, 'create'), (1, 'update'), (2, 'delete'), (3, 'access')], max_length=20, verbose_name='Action'),
        ),
    ]
