# Generated by Django 4.1.3 on 2023-01-15 21:33

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_directory_sub_directory"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="directory",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="directory",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="directoryevent",
            name="sub_directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_constraint=False,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.directory",
                verbose_name="Sub directory",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="directory",
            name="sub_directory",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="directory",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_directoryevent" ("created_at", "created_by_id", "id", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sub_directory_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sub_directory_id"); RETURN NULL;',
                    hash="027c6a58e1fec90614678524e442667a4efee971",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_1b3ea",
                    table="core_directory",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="directory",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_directoryevent" ("created_at", "created_by_id", "id", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sub_directory_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."sub_directory_id"); RETURN NULL;',
                    hash="e660f610174a30e30f6e348561053820c9b02dcf",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_26ded",
                    table="core_directory",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="directory",
            name="sub_directory",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.directory",
                verbose_name="Sub directory",
            ),
            preserve_default=False,
        ),
    ]
