# Generated by Django 4.2.20 on 2025-04-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_status_color_status_created_at_status_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="replies",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reply",
                "verbose_name_plural": "Replies",
            },
        ),
    ]
