# Generated by Django 4.1.3 on 2023-01-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_directory_snapshot_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="sub_directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.directory",
                verbose_name="Sub directory",
            ),
        ),
        migrations.AlterField(
            model_name="directoryevent",
            name="sub_directory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.directory",
                verbose_name="Sub directory",
            ),
        ),
    ]
