# Generated by Django 4.2.20 on 2025-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_comments_options_alter_replies_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorities",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "primary"),
                    ("secondary", "secondary"),
                    ("success", "success"),
                    ("info", "info"),
                    ("warning", "warning"),
                    ("danger", "danger"),
                    ("light", "light"),
                    ("dark", "dark"),
                ],
                default="primary",
                max_length=250,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="priorities",
            name="icon",
            field=models.CharField(
                default="bi bi-bootstrap", max_length=250, verbose_name="Icon"
            ),
        ),
    ]
