# Generated by Django 4.2.20 on 2025-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_priorities_color_priorities_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priorities",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                    ("Low", "Low"),
                ],
                max_length=250,
                verbose_name="Priority",
            ),
        ),
    ]
