# Generated by Django 4.2.20 on 2025-05-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_priorities_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("Resolved", "Resolved"),
                    ("Dismissed", "Dismissed"),
                    ("Suspended", "Suspended"),
                    ("Closed", "Closed"),
                    ("Nullified", "Nullified"),
                    ("In Progress", "In Progress"),
                    ("New", "New"),
                ],
                max_length=250,
                verbose_name="Status",
            ),
        ),
    ]
