# Generated by Django 4.2.20 on 2025-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_status_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
    ]
