# Generated by Django 4.2.20 on 2025-05-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0022_path_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_createdby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
