# Generated by Django 4.2.20 on 2025-06-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_contracts_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="extracted_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Extracted OCR Text"
            ),
        ),
        migrations.CreateModel(
            name="documentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="documents/pages/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.documents",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="documentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="documents/%Y/%m/%d/pages/")),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.documents",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "unique_together": {("document", "page_number")},
            },
        ),
    ]
