# Generated by Django 4.1.3 on 2023-01-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_documents_snapshot_insert_and_more'),
        ('core', '0023_remove_documents_snapshot_insert_and_more'),
    ]

    operations = [
    ]
