# Generated by Django 4.2.20 on 2025-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_documents_extracted_text_documentimage_documentpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y/%m/%d/",
                verbose_name="PDF",
            ),
        ),
    ]
