# Generated by Django 4.1.3 on 2023-04-05 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pghistory', '0005_events_middlewareevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='hearing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Litigation Case')),
                ('folder_id', models.IntegerField(blank=True, null=True, verbose_name='Folder')),
                ('hearing_date', models.DateTimeField(verbose_name='Hearing Date')),
                ('comments_by_lawyer', models.TextField(blank=True, max_length=250, null=True, verbose_name='Summary by lawyer')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('latest', models.BooleanField(default=True, verbose_name='Latest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hearing',
                'verbose_name_plural': 'Hearings',
            },
        ),
        migrations.CreateModel(
            name='HearingEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Litigation Case')),
                ('folder_id', models.IntegerField(blank=True, null=True, verbose_name='Folder')),
                ('hearing_date', models.DateTimeField(verbose_name='Hearing Date')),
                ('comments_by_lawyer', models.TextField(blank=True, max_length=250, null=True, verbose_name='Summary by lawyer')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('latest', models.BooleanField(default=True, verbose_name='Latest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Task Description')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Litigation Case')),
                ('folder_id', models.IntegerField(blank=True, null=True, verbose_name='Folder')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Task Description')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Litigation Case')),
                ('folder_id', models.IntegerField(blank=True, null=True, verbose_name='Folder')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='activities.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
