# Generated by Django 4.1.2 on 2022-10-20 10:38

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250, verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='hearing_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250, verbose_name='Hearing Type')),
            ],
            options={
                'verbose_name': 'Hearing Type',
                'verbose_name_plural': 'Hearing Types',
            },
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250, verbose_name='Task Type')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=20, verbose_name='Task ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(default='', verbose_name='Task Description')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('comments', models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priorities', verbose_name='Matter Priority')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task_type', verbose_name='Task Type')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='hearing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.CharField(max_length=20, verbose_name='Hearing ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('hearing_date', models.DateTimeField(verbose_name='Hearing Date')),
                ('time_spent', models.TimeField(verbose_name='Time Spent')),
                ('summary_by_lawyer', models.TextField(max_length=250, verbose_name='Summary by lawyer')),
                ('attachment', models.FileField(upload_to='hearing/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Attachment')),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('comments', models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments')),
                ('hearing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.hearing_type', verbose_name='Hearing Type')),
            ],
            options={
                'verbose_name': 'Hearing',
                'verbose_name_plural': 'Hearings',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(blank=True, max_length=20, null=True, verbose_name='Event ID')),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From')),
                ('to_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='To')),
                ('attendees', models.ManyToManyField(related_name='%(class)s_attendees', to=settings.AUTH_USER_MODEL, verbose_name='Attendees')),
                ('comments', models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.event_type', verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
