# Generated by Django 4.1.2 on 2022-10-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments_case'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments'),
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='comments',
        ),
        migrations.AddField(
            model_name='hearing',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments'),
        ),
    ]
