# Generated by Django 4.1.2 on 2022-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_hearing_created_at_hearing_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='hearing_type',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='hid',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='summary_by_lawyer',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tid',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Task Description'),
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='event_type',
        ),
        migrations.DeleteModel(
            name='hearing_type',
        ),
        migrations.DeleteModel(
            name='task_type',
        ),
    ]
