# Generated by Django 4.1.2 on 2022-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_case_comments_case_id_comments_event_id_and_more'),
        ('activities', '0003_alter_event_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments'),
        ),
    ]
