# Generated by Django 4.1.2 on 2022-10-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_hearing_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='comments',
        ),
        migrations.AddField(
            model_name='hearing',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Litigation Case'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='comments_by_lawyer',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Summary by lawyer'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
    ]
