# Generated by Django 4.2.20 on 2025-03-10 05:46

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_task_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearingevent',
            name='court',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='hearing_status',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='hearingevent',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='task_status',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='hearing',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='hearing',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='snapshot_update',
        ),
        migrations.DeleteModel(
            name='HearingEvent',
        ),
        migrations.DeleteModel(
            name='TaskEvent',
        ),
    ]
