# Generated by Django 4.1.2 on 2022-10-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court'),
        ('activities', '0004_remove_hearing_comments_hearing_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.court', verbose_name='Court name'),
        ),
    ]
