# Generated by Django 4.2.20 on 2025-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_remove_hearingevent_court_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_category",
            field=models.CharField(
                choices=[("Public", "Public"), ("Private", "Private")],
                default="Public",
                max_length=500,
                verbose_name="Task Category",
            ),
        ),
    ]
