# Generated by Django 4.1.2 on 2022-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_hearing_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='title'),
            preserve_default=False,
        ),
    ]
