# Generated by Django 4.1.2 on 2022-11-03 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0006_remove_task_name_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='assignee',
        ),
        migrations.AddField(
            model_name='hearing',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
    ]
