# Generated by Django 4.1.2 on 2022-11-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_hearing_assignee_hearing_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assigned',
        ),
    ]
