# Generated by Django 4.1.2 on 2022-11-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_rename_assigned_to_task_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assignee',
        ),
    ]
