# Generated by Django 4.1.3 on 2022-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_hearing_comments_task_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
