# Generated by Django 4.1.3 on 2022-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_hearing_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
