# Generated by Django 4.1.3 on 2023-01-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_hearing_snapshot_insert_and_more'),
        ('activities', '0019_remove_hearing_snapshot_insert_and_more'),
    ]

    operations = [
    ]
