# Generated by Django 4.1.3 on 2022-11-10 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='case_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
            },
        ),
        migrations.CreateModel(
            name='client_position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Client Position',
                'verbose_name_plural': 'Client Positions',
            },
        ),
        migrations.CreateModel(
            name='opponent_position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Opponent Position',
                'verbose_name_plural': 'Opponent Positions',
            },
        ),
        migrations.CreateModel(
            name='stages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='LitigationCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject')),
                ('case_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Case Category')),
                ('judge', models.CharField(blank=True, max_length=500, null=True, verbose_name='Judge Name')),
                ('detective', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detective')),
                ('internal_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('Stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.stages', verbose_name='Stage')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case_type', verbose_name='Case type')),
                ('client_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.client_position', verbose_name='Client Position')),
                ('comments', models.ManyToManyField(blank=True, to='core.comments', verbose_name='Comments')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.court', verbose_name='Court name')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, to='core.documents', verbose_name='Hearing')),
                ('hearing', models.ManyToManyField(blank=True, to='activities.hearing', verbose_name='Hearing')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('opponent_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.opponent_position', verbose_name='Opponent Position')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.priorities', verbose_name='Matter Priority')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='%(class)s_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('tasks', models.ManyToManyField(blank=True, related_name='%(class)s_task', to='activities.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Litigation Case',
                'verbose_name_plural': 'Litigation Cases',
            },
        ),
    ]
