# Generated by Django 4.1.3 on 2023-04-05 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pghistory', '0005_events_middlewareevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
            },
        ),
        migrations.CreateModel(
            name='CaseTypeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('type', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='client_position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Client Position',
                'verbose_name_plural': 'Client Positions',
            },
        ),
        migrations.CreateModel(
            name='ClientPositionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('Folder', 'Folder'), ('Administrative_investigations', 'Administrative investigations'), ('Notation', 'Notation')], default='Folder', max_length=100, verbose_name='Record Type')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject')),
                ('folder_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Folder Category')),
                ('internal_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='FolderEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('record_type', models.CharField(choices=[('Folder', 'Folder'), ('Administrative_investigations', 'Administrative investigations'), ('Notation', 'Notation')], default='Folder', max_length=100, verbose_name='Record Type')),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject')),
                ('folder_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Folder Category')),
                ('internal_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportantDevelopment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('case_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Important Development',
                'verbose_name_plural': 'Important Developments',
            },
        ),
        migrations.CreateModel(
            name='ImportantDevelopmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('case_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LitigationCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject')),
                ('case_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Case Category')),
                ('judge', models.CharField(blank=True, max_length=500, null=True, verbose_name='Judge Name')),
                ('detective', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detective')),
                ('internal_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Litigation Case',
                'verbose_name_plural': 'Litigation Cases',
            },
        ),
        migrations.CreateModel(
            name='opponent_position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Opponent Position',
                'verbose_name_plural': 'Opponent Positions',
            },
        ),
        migrations.CreateModel(
            name='stages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='StagesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='cases.stages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpponentPositionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='cases.opponent_position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LitigationCasesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject')),
                ('case_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Case Category')),
                ('judge', models.CharField(blank=True, max_length=500, null=True, verbose_name='Judge Name')),
                ('detective', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detective')),
                ('internal_ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('Stage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cases.stages', verbose_name='Stage')),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
