# Generated by Django 4.1.2 on 2022-10-11 07:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies_address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Iraq', max_length=2, null=True, verbose_name='Country'),
        ),
    ]
