# Generated by Django 4.1.2 on 2022-10-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_litigationcases_end_time_litigationcases_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='companies_address',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_group',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_legal_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='case_status',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='company',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='due_date',
        ),
        # migrations.RemoveField(
        #     model_name='litigationcases',
        #     name='event',
        # ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='filed_on',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='person',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='practice_area',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='case_status',
        ),
        migrations.DeleteModel(
            name='companies_address',
        ),
        migrations.DeleteModel(
            name='companies_category',
        ),
        migrations.DeleteModel(
            name='companies_group',
        ),
        migrations.DeleteModel(
            name='companies_sub_category',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='company_legal_type',
        ),
        migrations.DeleteModel(
            name='persons',
        ),
        migrations.DeleteModel(
            name='practice_area',
        ),
    ]
