# Generated by Django 4.1.3 on 2023-05-09 10:22

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='importantdevelopment',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='importantdevelopment',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='importantdevelopment',
            name='folder_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importantdevelopmentevent',
            name='folder_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importantdevelopment',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;', hash='1a0e488403e6fc44f6ec3a445c5b6e82d5d27056', operation='INSERT', pgid='pgtrigger_snapshot_insert_2be47', table='cases_importantdevelopment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importantdevelopment',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."case_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;', hash='37399385fbb9f52ece94176dd5b0d8246364012a', operation='UPDATE', pgid='pgtrigger_snapshot_update_09b9f', table='cases_importantdevelopment', when='AFTER')),
        ),
    ]
