# Generated by Django 4.1.2 on 2022-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_companies_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='cid',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Case ID'),
        ),
    ]
