# Generated by Django 4.1.2 on 2022-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_litigationcases_detective_litigationcases_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject'),
        ),
    ]
