# Generated by Django 4.1.3 on 2024-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_administrativeinvestigation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantdevelopment',
            options={'ordering': ['created_at'], 'verbose_name': 'Important Development', 'verbose_name_plural': 'Important Developments'},
        ),
        migrations.AlterField(
            model_name='importantdevelopment',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='importantdevelopmentevent',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='litigationcasesevent',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='notation',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notationevent',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
