# Generated by Django 4.1.2 on 2022-10-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cases', '0004_alter_litigationcases_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Assigned Team'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='client_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.client_position', verbose_name='Client Position'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='internal_ref_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Ref Number'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='opponent_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.opponent_position', verbose_name='Opponent Position'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.practice_area', verbose_name='Practice area'),
        ),
    ]
