# Generated by Django 4.1.3 on 2023-01-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_status'),
        ('cases', '0005_remove_litigationcases_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='case_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_case_status', to='core.status', verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='litigationcasesevent',
            name='case_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.status', verbose_name='Case Status'),
        ),
    ]
