# Generated by Django 4.1.3 on 2024-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_importantdevelopment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='ImportantDevelopment',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_ImportantDevelopment', to='cases.importantdevelopment', verbose_name='Important Development'),
        ),
    ]
