# Generated by Django 4.1.2 on 2022-10-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_litigationcases_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='practice_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Practice Area',
                'verbose_name_plural': 'Practice Areas',
            },
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.practice_area', verbose_name='Practice area'),
        ),
    ]
