# Generated by Django 4.1.2 on 2022-10-11 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_comments_id_alter_priorities_id'),
        ('cases', '0005_alter_litigationcases_assigned_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='Stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.stages', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_opponent', to='cases.persons', verbose_name='Opponent'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.priorities', verbose_name='Matter Priority'),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
    ]
