# Generated by Django 4.1.3 on 2024-06-14 12:17

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_litigationcases_importantdevelopment'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='importantdevelopment',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='importantdevelopment',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='importantdevelopment',
            name='contract_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importantdevelopmentevent',
            name='contract_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importantdevelopment',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_importantdevelopmentevent" ("admin_id", "case_id", "contract_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "notation_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."admin_id", NEW."case_id", NEW."contract_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."notation_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;', hash='70d6a41001561ae1b72e6e9615ab4f24a46d6550', operation='INSERT', pgid='pgtrigger_snapshot_insert_2be47', table='cases_importantdevelopment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importantdevelopment',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_importantdevelopmentevent" ("admin_id", "case_id", "contract_id", "created_at", "created_by_id", "folder_id", "id", "is_deleted", "modified_at", "modified_by_id", "notation_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."admin_id", NEW."case_id", NEW."contract_id", NEW."created_at", NEW."created_by_id", NEW."folder_id", NEW."id", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."notation_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;', hash='f0bebe30c8324bcb3c12a6c439244909023b71cb', operation='UPDATE', pgid='pgtrigger_snapshot_update_09b9f', table='cases_importantdevelopment', when='AFTER')),
        ),
    ]
