# Generated by Django 4.1.2 on 2022-10-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_practice_area_litigationcases_practice_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='practice_area',
            new_name='case_type',
        ),
        migrations.RenameField(
            model_name='case_type',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='practice_area',
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case_type', verbose_name='Case type'),
        ),
    ]
