# Generated by Django 4.1.2 on 2022-10-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_litigationcases_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Case Category',
                'verbose_name_plural': 'Case Categories',
            },
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='case_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.case_category', verbose_name='Case Category'),
            preserve_default=False,
        ),
    ]
