# Generated by Django 4.1.2 on 2022-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cases', '0007_rename_practice_area_case_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='core.comments', verbose_name='Comments'),
        ),
    ]
