# Generated by Django 4.1.3 on 2024-07-13 05:38

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_importantdevelopment_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='litigationcases',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='litigationcases',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='case_close_comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Case Close Comment'),
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='case_close_status',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], default='Won', max_length=10, null=True, verbose_name='Case Close Status'),
        ),
        migrations.AddField(
            model_name='litigationcasesevent',
            name='case_close_comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Case Close Comment'),
        ),
        migrations.AddField(
            model_name='litigationcasesevent',
            name='case_close_status',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], default='Won', max_length=10, null=True, verbose_name='Case Close Status'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='litigationcases',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_close_comment", "case_close_status", "case_status_id", "case_type_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_close_comment", NEW."case_close_status", NEW."case_status_id", NEW."case_type_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='3fe70caaac489e56340102df2f3a34ed5aa46fac', operation='INSERT', pgid='pgtrigger_snapshot_insert_38763', table='cases_litigationcases', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='litigationcases',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_close_comment", "case_close_status", "case_status_id", "case_type_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_close_comment", NEW."case_close_status", NEW."case_status_id", NEW."case_type_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='b30ce6cb502c0853fd91e9251da85bcc6a005576', operation='UPDATE', pgid='pgtrigger_snapshot_update_80525', table='cases_litigationcases', when='AFTER')),
        ),
    ]
