# Generated by Django 4.1.3 on 2023-01-24 08:48

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_documents_snapshot_insert_and_more'),
        ('cases', '0007_importantdevelopment_importantdevelopmentevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder_status', to='core.status', verbose_name='Folder Status'),
        ),
        migrations.AddField(
            model_name='folderevent',
            name='folder_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.status', verbose_name='Folder Status'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_folderevent" ("Stage_id", "assignee_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='00442f65504557d32c061bc00752bd80b14175b7', operation='INSERT', pgid='pgtrigger_snapshot_insert_72454', table='cases_folder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_folderevent" ("Stage_id", "assignee_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='fb0e7123c54aa99ada15695f000e2bf05bdbb24a', operation='UPDATE', pgid='pgtrigger_snapshot_update_9f4aa', table='cases_folder', when='AFTER')),
        ),
    ]
