# Generated by Django 4.1.2 on 2022-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_category_litigationcases_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='case_category',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=500, verbose_name='Case Category'),
        ),
        migrations.DeleteModel(
            name='case_category',
        ),
    ]
