# Generated by Django 4.1.3 on 2023-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_folder_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='litigationcases',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='litigationcasesevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='litigationcasesevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
