# Generated by Django 4.1.3 on 2024-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_litigationcases_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_type',
            name='stage',
            field=models.ManyToManyField(blank=True, null=True, related_name='stages', to='cases.stages'),
        ),
    ]
