# Generated by Django 4.1.3 on 2024-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_type_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_type',
            name='stage',
            field=models.ManyToManyField(blank=True, related_name='case_types', to='cases.stages'),
        ),
    ]
