# Generated by Django 4.1.2 on 2022-10-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documents_contracts'),
        ('cases', '0009_alter_litigationcases_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigationcases',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documents', verbose_name='Documents'),
        ),
    ]
