# Generated by Django 4.1.2 on 2022-10-18 08:36

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_litigationcases_case_category_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='practice_areaTranslation',
            fields=[
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cases.practice_area')),
            ],
            options={
                'verbose_name': 'Practice Area Translation',
                'db_table': 'cases_practice_area_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
    ]
