# Generated by Django 4.1.3 on 2023-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_path_snapshot_insert_and_more'),
        ('cases', '0010_litigationcases_paths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='Paths',
            field=models.ManyToManyField(blank=True, to='core.path', verbose_name='Paths'),
        ),
    ]
