# Generated by Django 4.1.3 on 2024-07-29 05:11

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('cases', '0010_alter_case_type_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='characteristic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='litigationcases',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='litigationcases',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='litigationcases',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_close_comment", "case_close_status", "case_status_id", "case_type_id", "characteristic_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_close_comment", NEW."case_close_status", NEW."case_status_id", NEW."case_type_id", NEW."characteristic_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='2a9738013e72fba8463ea07357de6e44332bccce', operation='INSERT', pgid='pgtrigger_snapshot_insert_38763', table='cases_litigationcases', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='litigationcases',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_close_comment", "case_close_status", "case_status_id", "case_type_id", "characteristic_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_close_comment", NEW."case_close_status", NEW."case_status_id", NEW."case_type_id", NEW."characteristic_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='47fdcd7b4f9640abbdf4df50790c540a5b69ae6f', operation='UPDATE', pgid='pgtrigger_snapshot_update_80525', table='cases_litigationcases', when='AFTER')),
        ),
        migrations.AddField(
            model_name='characteristicevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='characteristicevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='cases.characteristic'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='characteristic',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_characteristicevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='82702d689ae38591ff9b6cc21d4eb5fcbe820038', operation='INSERT', pgid='pgtrigger_snapshot_insert_1ad50', table='cases_characteristic', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='characteristic',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_characteristicevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='9efebdf64937f1637c6e1f13a66fee6c32bb528b', operation='UPDATE', pgid='pgtrigger_snapshot_update_580a5', table='cases_characteristic', when='AFTER')),
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.characteristic', verbose_name='Case characteristic'),
        ),
        migrations.AddField(
            model_name='litigationcasesevent',
            name='characteristic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cases.characteristic', verbose_name='Case characteristic'),
        ),
    ]
