# Generated by Django 4.1.3 on 2023-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_litigationcases_paths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigationcases',
            old_name='Paths',
            new_name='paths',
        ),
    ]
