# Generated by Django 4.1.2 on 2022-10-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court'),
        ('cases', '0012_alter_case_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.court', verbose_name='Court name'),
        ),
        migrations.DeleteModel(
            name='court',
        ),
    ]
