# Generated by Django 4.1.3 on 2024-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_characteristic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='case_close_status',
            field=models.CharField(blank=True, choices=[('رابحة', 'رابحة'), ('خاسرة', 'خاسرة')], default='', max_length=10, null=True, verbose_name='Case Close Status'),
        ),
        migrations.AlterField(
            model_name='litigationcasesevent',
            name='case_close_status',
            field=models.CharField(blank=True, choices=[('رابحة', 'رابحة'), ('خاسرة', 'خاسرة')], default='', max_length=10, null=True, verbose_name='Case Close Status'),
        ),
    ]
