# Generated by Django 4.1.3 on 2023-02-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_path_snapshot_insert_and_more'),
        ('cases', '0012_rename_paths_litigationcases_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='paths',
            field=models.ManyToManyField(blank=True, to='core.path', verbose_name='Paths'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.documents', verbose_name='Documents'),
        ),
    ]
