# Generated by Django 4.1.3 on 2023-02-09 06:09

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_folder_paths_alter_folder_documents'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_update',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='cases_folde_id_acb0e2_idx',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='client_position',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='detective',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='opponent_position',
        ),
        migrations.RemoveField(
            model_name='folderevent',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='folderevent',
            name='client_position',
        ),
        migrations.RemoveField(
            model_name='folderevent',
            name='detective',
        ),
        migrations.RemoveField(
            model_name='folderevent',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='folderevent',
            name='opponent_position',
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['id', 'name', 'folder_type', 'folder_category', 'assignee', 'court', 'description'], name='cases_folde_id_b5cdd8_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_folderevent" ("assignee_id", "court_id", "created_at", "created_by_id", "description", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."assignee_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='af91251fbeed1a0efd67d52cc1df43f398284c5d', operation='INSERT', pgid='pgtrigger_snapshot_insert_72454', table='cases_folder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_folderevent" ("assignee_id", "court_id", "created_at", "created_by_id", "description", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."assignee_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;', hash='baaf03aa0a086ed464e9795fd90d533625a33cf6', operation='UPDATE', pgid='pgtrigger_snapshot_update_9f4aa', table='cases_folder', when='AFTER')),
        ),
    ]
