# Generated by Django 4.1.2 on 2022-11-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documents_attachment'),
        ('cases', '0013_alter_litigationcases_court_delete_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigationcases',
            name='documents',
        ),
        migrations.AddField(
            model_name='litigationcases',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.documents', verbose_name='Hearing'),
        ),
    ]
