# Generated by Django 4.1.3 on 2023-02-27 07:52

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_remove_folder_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='folder',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='folder',
            name='record_type',
            field=models.CharField(choices=[('Folder', 'Folder'), ('Administrative_investigations', 'Administrative investigations'), ('Notation', 'Notation')], default='Folder', max_length=100, verbose_name='Record Type'),
        ),
        migrations.AddField(
            model_name='folderevent',
            name='record_type',
            field=models.CharField(choices=[('Folder', 'Folder'), ('Administrative_investigations', 'Administrative investigations'), ('Notation', 'Notation')], default='Folder', max_length=100, verbose_name='Record Type'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cases_folderevent" ("assignee_id", "court_id", "created_at", "created_by_id", "description", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "record_type", "start_time") VALUES (NEW."assignee_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."record_type", NEW."start_time"); RETURN NULL;', hash='d7c533f3a587ebc2be2dd6ad42be8ac63daf9a8a', operation='INSERT', pgid='pgtrigger_snapshot_insert_72454', table='cases_folder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folder',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cases_folderevent" ("assignee_id", "court_id", "created_at", "created_by_id", "description", "end_time", "folder_category", "folder_status_id", "folder_type_id", "id", "internal_ref_number", "is_deleted", "modified_at", "modified_by_id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "record_type", "start_time") VALUES (NEW."assignee_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."end_time", NEW."folder_category", NEW."folder_status_id", NEW."folder_type_id", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."modified_at", NEW."modified_by_id", NEW."name", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."record_type", NEW."start_time"); RETURN NULL;', hash='33b8087e658f687eca91bd2ffd218f9688c55da1', operation='UPDATE', pgid='pgtrigger_snapshot_update_9f4aa', table='cases_folder', when='AFTER')),
        ),
    ]
