# Generated by Django 4.2.20 on 2025-04-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_alter_litigationcases_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcases',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.characteristic', verbose_name='Case characteristic'),
        ),
        migrations.AlterField(
            model_name='notation',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
