# Generated by Django 4.2.20 on 2025-04-29 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0017_alter_litigationcases_characteristic_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importantdevelopment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Important Development",
                "verbose_name_plural": "Important Developments",
            },
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="created_at",
            field=models.DateTimeField(editable=False, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_createdby",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modifiedby",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="litigationcases",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start time"
            ),
        ),
    ]
