# Generated by Django 4.1.3 on 2023-01-11 07:33

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_status"),
        ("cases", "0019_folder_folderevent_folder_cases_folde_id_acb0e2_idx_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="litigationcases",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="litigationcases",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="litigationcases",
            name="case_status",
            field=models.ForeignKey(
                default="",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_case_status",
                to="core.status",
                verbose_name="Case Status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="litigationcasesevent",
            name="case_status",
            field=models.ForeignKey(
                db_constraint=False,
                default="",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.status",
                verbose_name="Case Status",
            ),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="litigationcases",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_status_id", "case_type_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_status_id", NEW."case_type_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;',
                    hash="42548b2d6b4e6c19c9bebbc7880b7775af0cf4c7",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_38763",
                    table="cases_litigationcases",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="litigationcases",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "cases_litigationcasesevent" ("Stage_id", "assignee_id", "case_category", "case_status_id", "case_type_id", "client_position_id", "court_id", "created_at", "created_by_id", "description", "detective", "end_time", "id", "internal_ref_number", "is_deleted", "judge", "modified_at", "modified_by_id", "name", "opponent_position_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_id", "start_time") VALUES (NEW."Stage_id", NEW."assignee_id", NEW."case_category", NEW."case_status_id", NEW."case_type_id", NEW."client_position_id", NEW."court_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."detective", NEW."end_time", NEW."id", NEW."internal_ref_number", NEW."is_deleted", NEW."judge", NEW."modified_at", NEW."modified_by_id", NEW."name", NEW."opponent_position_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."priority_id", NEW."start_time"); RETURN NULL;',
                    hash="22272ff8ef6b9c9a5610e3c5992b4e399479a509",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_80525",
                    table="cases_litigationcases",
                    when="AFTER",
                ),
            ),
        ),
    ]
