# Generated by Django 4.2.20 on 2025-05-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_alter_administrativeinvestigation_paths_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="litigationcases",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
        migrations.AddField(
            model_name="litigationcases",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="cases.litigationcases",
            ),
        ),
    ]
