# Generated by Django 4.2.20 on 2025-05-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_litigationcases_is_archived_litigationcases_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litigationcases",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child",
                to="cases.litigationcases",
            ),
        ),
    ]
