# Generated by Django 4.1.3 on 2023-01-15 20:44

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_importantdevelopment_importantdevelopmentevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="importantdevelopment",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="importantdevelopment",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="importantdevelopment",
            name="case_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importantdevelopment",
            name="event_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importantdevelopment",
            name="task_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importantdevelopmentevent",
            name="case_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importantdevelopmentevent",
            name="event_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importantdevelopmentevent",
            name="task_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="importantdevelopment",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "event_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id", "title") VALUES (NEW."case_id", NEW."event_id", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."task_id", NEW."title"); RETURN NULL;',
                    hash="48ae0d32581561f0d2ada1d0f003a16e71d7820c",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_2be47",
                    table="cases_importantdevelopment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="importantdevelopment",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "event_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id", "title") VALUES (NEW."case_id", NEW."event_id", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."task_id", NEW."title"); RETURN NULL;',
                    hash="fb06e54340331262400bd8ebbb204e3f3a5a3c15",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_09b9f",
                    table="cases_importantdevelopment",
                    when="AFTER",
                ),
            ),
        ),
    ]
