# Generated by Django 4.1.3 on 2023-01-15 20:48

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_remove_importantdevelopment_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="importantdevelopment",
            name="snapshot_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="importantdevelopment",
            name="snapshot_update",
        ),
        migrations.RemoveField(
            model_name="importantdevelopment",
            name="event_id",
        ),
        migrations.RemoveField(
            model_name="importantdevelopment",
            name="task_id",
        ),
        migrations.RemoveField(
            model_name="importantdevelopmentevent",
            name="event_id",
        ),
        migrations.RemoveField(
            model_name="importantdevelopmentevent",
            name="task_id",
        ),
        migrations.AddField(
            model_name="importantdevelopment",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="importantdevelopmentevent",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="importantdevelopment",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "id", "is_deleted", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."case_id", NEW."id", NEW."is_deleted", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;',
                    hash="c5241fe8f46286401328125876a7c01f7cb60e21",
                    operation="INSERT",
                    pgid="pgtrigger_snapshot_insert_2be47",
                    table="cases_importantdevelopment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="importantdevelopment",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "cases_importantdevelopmentevent" ("case_id", "id", "is_deleted", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."case_id", NEW."id", NEW."is_deleted", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."title"); RETURN NULL;',
                    hash="02bece6e284c12f74434deded1a7ca7631ed92e7",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_09b9f",
                    table="cases_importantdevelopment",
                    when="AFTER",
                ),
            ),
        ),
    ]
