# Generated by Django 4.1.3 on 2023-01-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_remove_folder_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='litigationcases',
            name='tasks',
        ),
    ]
