# Generated by Django 4.1.3 on 2023-01-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_folder_snapshot_insert_and_more'),
        ('cases', '0029_remove_folder_hearing_remove_folder_tasks_and_more'),
    ]

    operations = [
    ]
