API_VERSION = '4'
DEFAULT_DYNAMIC_FIELD_SEPARATOR = '__'
DEFAULT_PAGE_SIZE_QUERY_PARAMETER = 'page_size'
DEFAULT_REST_API_DISABLE_LINKS = False
DEFAULT_REST_API_MAXIMUM_PAGE_SIZE = 100
DEFAULT_REST_API_PAGE_SIZE = 10

QUERY_FIELD_EXCLUDE_PARAMETER = '_fields_exclude'
QUERY_FIELD_ONLY_PARAMETER = '_fields_only'
DEFAULT_VIEWS_PAGINATE_BY = 30
DEFAULT_VIEWS_PAGING_ARGUMENT = 'page'
DEFAULT_VIEWS_SHOW_DROPZONE_SUBMIT_BUTTON = False

LIST_MODE_CHOICE_LIST = 'list'
LIST_MODE_CHOICE_ITEM = 'item'

PK_LIST_SEPARATOR = ','

TEXT_LIST_AS_ITEMS_PARAMETER = '_list_mode'
TEXT_LIST_AS_ITEMS_VARIABLE_NAME = 'list_as_items'
TEXT_CHOICE_ITEMS = 'items'
TEXT_CHOICE_LIST = 'list'

TEXT_SORT_FIELD_PARAMETER = '_ordering'
TEXT_SORT_FIELD_VARIABLE_NAME = 'ordering'
