# Generated by Django 4.1.3 on 2023-04-25 08:49

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_update',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userevent',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userevent',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_userevent" ("Manager_id", "created_at", "created_by_id", "date_joined", "email", "email_notification", "first_name", "i_agree", "id", "is_active", "is_admin", "is_blocked", "is_manager", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "modified_at", "modified_by_id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "photo", "thumbnail", "username") VALUES (NEW."Manager_id", NEW."created_at", NEW."created_by_id", NEW."date_joined", NEW."email", NEW."email_notification", NEW."first_name", NEW."i_agree", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_blocked", NEW."is_manager", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."modified_at", NEW."modified_by_id", NEW."password", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."phone", NEW."photo", NEW."thumbnail", NEW."username"); RETURN NULL;', hash='f2692eb8d460bbf59913ef700033d8b694aa0f45', operation='INSERT', pgid='pgtrigger_snapshot_insert_5efe8', table='accounts_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounts_userevent" ("Manager_id", "created_at", "created_by_id", "date_joined", "email", "email_notification", "first_name", "i_agree", "id", "is_active", "is_admin", "is_blocked", "is_manager", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "modified_at", "modified_by_id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "photo", "thumbnail", "username") VALUES (NEW."Manager_id", NEW."created_at", NEW."created_by_id", NEW."date_joined", NEW."email", NEW."email_notification", NEW."first_name", NEW."i_agree", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_blocked", NEW."is_manager", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."modified_at", NEW."modified_by_id", NEW."password", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."phone", NEW."photo", NEW."thumbnail", NEW."username"); RETURN NULL;', hash='aa6aa7a569865196d067d28d2126c21498014651', operation='UPDATE', pgid='pgtrigger_snapshot_update_14ad6', table='accounts_user', when='AFTER')),
        ),
    ]
