# Generated by Django 4.1.3 on 2022-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Email Notification'),
        ),
    ]
