# Generated by Django 4.1.3 on 2023-05-09 09:27

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='user',
            name='is_cases_private_manager',
            field=models.BooleanField(default=False, verbose_name='Is Cases Private Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cases_public_manager',
            field=models.BooleanField(default=False, verbose_name='Is Cases Public Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contract_manager',
            field=models.BooleanField(default=False, verbose_name='Is Contract Manager'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='is_cases_private_manager',
            field=models.BooleanField(default=False, verbose_name='Is Cases Private Manager'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='is_cases_public_manager',
            field=models.BooleanField(default=False, verbose_name='Is Cases Public Manager'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='is_contract_manager',
            field=models.BooleanField(default=False, verbose_name='Is Contract Manager'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_userevent" ("Manager_id", "created_at", "created_by_id", "date_joined", "email", "email_notification", "first_name", "i_agree", "id", "is_active", "is_admin", "is_blocked", "is_cases_private_manager", "is_cases_public_manager", "is_contract_manager", "is_manager", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "modified_at", "modified_by_id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "photo", "thumbnail", "username") VALUES (NEW."Manager_id", NEW."created_at", NEW."created_by_id", NEW."date_joined", NEW."email", NEW."email_notification", NEW."first_name", NEW."i_agree", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_blocked", NEW."is_cases_private_manager", NEW."is_cases_public_manager", NEW."is_contract_manager", NEW."is_manager", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."modified_at", NEW."modified_by_id", NEW."password", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."phone", NEW."photo", NEW."thumbnail", NEW."username"); RETURN NULL;', hash='9b6aa03fa654e5ff9a4c9c4b67365f549b644f91', operation='INSERT', pgid='pgtrigger_snapshot_insert_5efe8', table='accounts_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounts_userevent" ("Manager_id", "created_at", "created_by_id", "date_joined", "email", "email_notification", "first_name", "i_agree", "id", "is_active", "is_admin", "is_blocked", "is_cases_private_manager", "is_cases_public_manager", "is_contract_manager", "is_manager", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "modified_at", "modified_by_id", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "photo", "thumbnail", "username") VALUES (NEW."Manager_id", NEW."created_at", NEW."created_by_id", NEW."date_joined", NEW."email", NEW."email_notification", NEW."first_name", NEW."i_agree", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_blocked", NEW."is_cases_private_manager", NEW."is_cases_public_manager", NEW."is_contract_manager", NEW."is_manager", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."modified_at", NEW."modified_by_id", NEW."password", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."phone", NEW."photo", NEW."thumbnail", NEW."username"); RETURN NULL;', hash='68bd20089dd1f110bd392ef477c788d90bef0831', operation='UPDATE', pgid='pgtrigger_snapshot_update_14ad6', table='accounts_user', when='AFTER')),
        ),
    ]
