# Generated by Django 4.1.3 on 2023-08-27 05:58

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('accounts', '0003_remove_user_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('full_info', models.JSONField(blank=True, null=True, verbose_name='Employee Full Info')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('full_info', models.JSONField(blank=True, null=True, verbose_name='Employee Full Info')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='accounts.employees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['full_name'], name='accounts_em_full_na_ff5ebd_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employees',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_employeesevent" ("email", "full_info", "full_name", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."email", NEW."full_info", NEW."full_name", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='c4eac3c7667d488ecb20897a930e1eddb453400a', operation='INSERT', pgid='pgtrigger_snapshot_insert_1b744', table='accounts_employees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='employees',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounts_employeesevent" ("email", "full_info", "full_name", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."email", NEW."full_info", NEW."full_name", NEW."id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='120298c61c9d81394217182497cc17f0551f656a', operation='UPDATE', pgid='pgtrigger_snapshot_update_59296', table='accounts_employees', when='AFTER')),
        ),
    ]
