# Generated by Django 4.2.20 on 2025-03-10 05:46

import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_snapshot_insert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='employeesevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='pgh_obj',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='employees',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='employees',
            name='snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='user',
            name='enable_transision',
            field=models.BooleanField(default=False, verbose_name='Enable transision'),
        ),
        migrations.DeleteModel(
            name='EmployeesEvent',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
