# Generated by Django 4.2.20 on 2025-03-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employeesevent_pgh_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enable_transision',
            field=models.BooleanField(default=True, verbose_name='Enable transision'),
        ),
    ]
