# Generated by Django 4.2.20 on 2025-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_enable_transision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5, verbose_name='Language'),
        ),
    ]
