# Generated by Django 4.2.20 on 2025-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_color",
            field=models.CharField(
                choices=[("light", "light"), ("dark", "dark")],
                default="light",
                max_length=5,
                verbose_name="Theme Color",
            ),
        ),
    ]
