# Generated by Django 4.2.20 on 2025-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_theme_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="enable_transision",),
        migrations.AddField(
            model_name="user",
            name="enable_transition",
            field=models.BooleanField(default=True, verbose_name="Enable transition"),
        ),
    ]
