# Generated by Django 4.2.20 on 2025-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_enable_transision_user_enable_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_grid",
            field=models.BooleanField(default=False, verbose_name="Files grid View"),
        ),
    ]
