# Generated by Django 4.2.20 on 2025-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_is_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_filter_show",
            field=models.BooleanField(
                default=False, verbose_name="Already show filters"
            ),
        ),
    ]
